//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESMEA_TMS.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TESMEA_TMS.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        internal static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tính toán.
        /// </summary>
        internal static string btn_Add_calculation {
            get {
                return ResourceManager.GetString("btn_Add_calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo dự án.
        /// </summary>
        internal static string btn_Add_project {
            get {
                return ResourceManager.GetString("btn_Add_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUAY LẠI.
        /// </summary>
        internal static string btn_Back {
            get {
                return ResourceManager.GetString("btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống template nhập dữ liệu.
        /// </summary>
        internal static string btn_Down_measure_template {
            get {
                return ResourceManager.GetString("btn_Down_measure_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT BÁO CÁO.
        /// </summary>
        internal static string btn_Export_report {
            get {
                return ResourceManager.GetString("btn_Export_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT KẾT QUẢ ĐO KIỂM.
        /// </summary>
        internal static string btn_Export_result {
            get {
                return ResourceManager.GetString("btn_Export_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾT THÚC.
        /// </summary>
        internal static string btn_Finish {
            get {
                return ResourceManager.GetString("btn_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẬP DỮ LIỆU ĐO KIỂM.
        /// </summary>
        internal static string btn_Import_measure {
            get {
                return ResourceManager.GetString("btn_Import_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string btn_Ok {
            get {
                return ResourceManager.GetString("btn_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi nhớ đăng nhập.
        /// </summary>
        internal static string ckb_RememberMe {
            get {
                return ResourceManager.GetString("ckb_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        internal static string col_Action {
            get {
                return ResourceManager.GetString("col_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng.
        /// </summary>
        internal static string col_Airflow {
            get {
                return ResourceManager.GetString("col_Airflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string col_Created_date {
            get {
                return ResourceManager.GetString("col_Created_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người tạo.
        /// </summary>
        internal static string col_Created_user {
            get {
                return ResourceManager.GetString("col_Created_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string col_Delete {
            get {
                return ResourceManager.GetString("col_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên library.
        /// </summary>
        internal static string col_Lib_name {
            get {
                return ResourceManager.GetString("col_Lib_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa.
        /// </summary>
        internal static string col_Modified_date {
            get {
                return ResourceManager.GetString("col_Modified_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người sửa.
        /// </summary>
        internal static string col_Modified_user {
            get {
                return ResourceManager.GetString("col_Modified_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string col_No {
            get {
                return ResourceManager.GetString("col_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu suất trên trục (kW).
        /// </summary>
        internal static string col_Power {
            get {
                return ResourceManager.GetString("col_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp suất tĩnh (Pa).
        /// </summary>
        internal static string col_Ps {
            get {
                return ResourceManager.GetString("col_Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp suất tổng (Pa).
        /// </summary>
        internal static string col_Pt {
            get {
                return ResourceManager.GetString("col_Pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Góc mở van (%).
        /// </summary>
        internal static string col_Scenario_cv {
            get {
                return ResourceManager.GetString("col_Scenario_cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ lệch chuẩn (%).
        /// </summary>
        internal static string col_Scenario_maxmin {
            get {
                return ResourceManager.GetString("col_Scenario_maxmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kịch bản.
        /// </summary>
        internal static string col_Scenario_name {
            get {
                return ResourceManager.GetString("col_Scenario_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tần số (%).
        /// </summary>
        internal static string col_Scenario_s {
            get {
                return ResourceManager.GetString("col_Scenario_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chờ ổn định (giây).
        /// </summary>
        internal static string col_Scenario_timerange {
            get {
                return ResourceManager.GetString("col_Scenario_timerange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu suất tĩnh (%).
        /// </summary>
        internal static string col_SEff {
            get {
                return ResourceManager.GetString("col_SEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        internal static string col_Select {
            get {
                return ResourceManager.GetString("col_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu suất tổng (%).
        /// </summary>
        internal static string col_TEff {
            get {
                return ResourceManager.GetString("col_TEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tác.
        /// </summary>
        internal static string col_Undo {
            get {
                return ResourceManager.GetString("col_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HỆ THỐNG ĐO KIỂM TỰ ĐỘNG ĐẶC TÍNH QUẠT CÔNG NGHIỆP.
        /// </summary>
        internal static string Common_AppName {
            get {
                return ResourceManager.GetString("Common_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN PHẨM THUỘC ĐỀ TÀI CẤP NHÀ NƯỚC MÃ SỐ: ĐTĐL.CN-63/23.
        /// </summary>
        internal static string Common_AppSubName {
            get {
                return ResourceManager.GetString("Common_AppSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn thoát ứng dụng?.
        /// </summary>
        internal static string Common_ExitMessage {
            get {
                return ResourceManager.GetString("Common_ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng ứng dụng.
        /// </summary>
        internal static string Common_ExitTitle {
            get {
                return ResourceManager.GetString("Common_ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        internal static string groupbox_Action {
            get {
                return ResourceManager.GetString("groupbox_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ống gió.
        /// </summary>
        internal static string groupbox_Duct {
            get {
                return ResourceManager.GetString("groupbox_Duct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        internal static string groupbox_General_infomation {
            get {
                return ResourceManager.GetString("groupbox_General_infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biến tần.
        /// </summary>
        internal static string groupbox_Inverter {
            get {
                return ResourceManager.GetString("groupbox_Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham số.
        /// </summary>
        internal static string groupbox_Parameter {
            get {
                return ResourceManager.GetString("groupbox_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string groupbox_Password {
            get {
                return ResourceManager.GetString("groupbox_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        internal static string groupbox_Report {
            get {
                return ResourceManager.GetString("groupbox_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin mẫu thử nghiệm.
        /// </summary>
        internal static string groupbox_Sample_information {
            get {
                return ResourceManager.GetString("groupbox_Sample_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kịch bản đo kiểm.
        /// </summary>
        internal static string groupbox_Scenario {
            get {
                return ResourceManager.GetString("groupbox_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách kịch bản.
        /// </summary>
        internal static string groupbox_Scenarios {
            get {
                return ResourceManager.GetString("groupbox_Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng thông số cảm biến.
        /// </summary>
        internal static string groupbox_Sensor {
            get {
                return ResourceManager.GetString("groupbox_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simatic/PLC.
        /// </summary>
        internal static string groupbox_Simatic {
            get {
                return ResourceManager.GetString("groupbox_Simatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đo kiểm.
        /// </summary>
        internal static string groupbox_Test_information {
            get {
                return ResourceManager.GetString("groupbox_Test_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn chọn đường dẫn lưu dự án.
        /// </summary>
        internal static string hint_Project_path {
            get {
                return ResourceManager.GetString("hint_Project_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng.
        /// </summary>
        internal static string lbl_Airflow {
            get {
                return ResourceManager.GetString("lbl_Airflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lượng khí thiết kế.
        /// </summary>
        internal static string lbl_Airflow_design {
            get {
                return ResourceManager.GetString("lbl_Airflow_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiệt độ môi trường.
        /// </summary>
        internal static string lbl_Ambient_temp {
            get {
                return ResourceManager.GetString("lbl_Ambient_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chuẩn áp dụng.
        /// </summary>
        internal static string lbl_Applied_standard {
            get {
                return ResourceManager.GetString("lbl_Applied_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiệt độ gối trục.
        /// </summary>
        internal static string lbl_Bearing_temp {
            get {
                return ResourceManager.GetString("lbl_Bearing_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ rung gối trục.
        /// </summary>
        internal static string lbl_Bearing_viab {
            get {
                return ResourceManager.GetString("lbl_Bearing_viab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng điện.
        /// </summary>
        internal static string lbl_Current {
            get {
                return ResourceManager.GetString("lbl_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đường dẫn file cơ sử dữ liệu.
        /// </summary>
        internal static string lbl_Db_path {
            get {
                return ResourceManager.GetString("lbl_Db_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiệt độ bầu khô.
        /// </summary>
        internal static string lbl_Dry_bulb_temp {
            get {
                return ResourceManager.GetString("lbl_Dry_bulb_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốc độ thiết kế của quạt.
        /// </summary>
        internal static string lbl_Fan_speed {
            get {
                return ResourceManager.GetString("lbl_Fan_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tần số.
        /// </summary>
        internal static string lbl_Frequency {
            get {
                return ResourceManager.GetString("lbl_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tần số động cơ theo thiết kế.
        /// </summary>
        internal static string lbl_Frequency_design {
            get {
                return ResourceManager.GetString("lbl_Frequency_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số đo kiểm.
        /// </summary>
        internal static string lbl_Library_type {
            get {
                return ResourceManager.GetString("lbl_Library_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở sản xuất.
        /// </summary>
        internal static string lbl_Manufacturer {
            get {
                return ResourceManager.GetString("lbl_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momen xoắn trên trục quạt.
        /// </summary>
        internal static string lbl_Momen {
            get {
                return ResourceManager.GetString("lbl_Momen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ số công suất động cơ.
        /// </summary>
        internal static string lbl_Motor_cosphi {
            get {
                return ResourceManager.GetString("lbl_Motor_cosphi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiệu suất động cơ.
        /// </summary>
        internal static string lbl_Motor_eff {
            get {
                return ResourceManager.GetString("lbl_Motor_eff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công suất động cơ.
        /// </summary>
        internal static string lbl_Motor_power {
            get {
                return ResourceManager.GetString("lbl_Motor_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện áp động cơ.
        /// </summary>
        internal static string lbl_Motor_voltage {
            get {
                return ResourceManager.GetString("lbl_Motor_voltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái hoạt động.
        /// </summary>
        internal static string lbl_Operating_status {
            get {
                return ResourceManager.GetString("lbl_Operating_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string lbl_Password_confirm {
            get {
                return ResourceManager.GetString("lbl_Password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string lbl_Password_new {
            get {
                return ResourceManager.GetString("lbl_Password_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiên tại.
        /// </summary>
        internal static string lbl_Password_old {
            get {
                return ResourceManager.GetString("lbl_Password_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập để tiếp tục.
        /// </summary>
        internal static string lbl_Please_login {
            get {
                return ResourceManager.GetString("lbl_Please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công suất.
        /// </summary>
        internal static string lbl_Power {
            get {
                return ResourceManager.GetString("lbl_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dự án.
        /// </summary>
        internal static string lbl_Project_name {
            get {
                return ResourceManager.GetString("lbl_Project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn lưu dự án.
        /// </summary>
        internal static string lbl_Project_path {
            get {
                return ResourceManager.GetString("lbl_Project_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string lbl_Quantity {
            get {
                return ResourceManager.GetString("lbl_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dòng điện định mức của động cơ.
        /// </summary>
        internal static string lbl_Rated_current {
            get {
                return ResourceManager.GetString("lbl_Rated_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận mẫu.
        /// </summary>
        internal static string lbl_Reception_date {
            get {
                return ResourceManager.GetString("lbl_Reception_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn mẫu báo cáo.
        /// </summary>
        internal static string lbl_Report_select {
            get {
                return ResourceManager.GetString("lbl_Report_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhận yêu cầu.
        /// </summary>
        internal static string lbl_Request_date {
            get {
                return ResourceManager.GetString("lbl_Request_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mẫu thử.
        /// </summary>
        internal static string lbl_Sample {
            get {
                return ResourceManager.GetString("lbl_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng mẫu.
        /// </summary>
        internal static string lbl_Sample_obser {
            get {
                return ResourceManager.GetString("lbl_Sample_obser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu.
        /// </summary>
        internal static string lbl_Sample_symbol {
            get {
                return ResourceManager.GetString("lbl_Sample_symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kịch bản kiểm thử.
        /// </summary>
        internal static string lbl_Scenario {
            get {
                return ResourceManager.GetString("lbl_Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến nhiệt độ môi trường.
        /// </summary>
        internal static string lbl_Sensor_Amb_temp {
            get {
                return ResourceManager.GetString("lbl_Sensor_Amb_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến lưu lượng.
        /// </summary>
        internal static string lbl_Sensor_flow {
            get {
                return ResourceManager.GetString("lbl_Sensor_flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến độ ẩm môi trường.
        /// </summary>
        internal static string lbl_Sensor_hu {
            get {
                return ResourceManager.GetString("lbl_Sensor_hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến áp suất.
        /// </summary>
        internal static string lbl_Sensor_pressure {
            get {
                return ResourceManager.GetString("lbl_Sensor_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dải đo cảm biến.
        /// </summary>
        internal static string lbl_Sensor_range {
            get {
                return ResourceManager.GetString("lbl_Sensor_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn tới Simatic/PLC.
        /// </summary>
        internal static string lbl_Simatic_path {
            get {
                return ResourceManager.GetString("lbl_Simatic_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tốc độ.
        /// </summary>
        internal static string lbl_Speed {
            get {
                return ResourceManager.GetString("lbl_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áp suất thiết kế.
        /// </summary>
        internal static string lbl_SPressure_design {
            get {
                return ResourceManager.GetString("lbl_SPressure_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiệt độ thiết kế làm việc.
        /// </summary>
        internal static string lbl_Temp_fluid {
            get {
                return ResourceManager.GetString("lbl_Temp_fluid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        internal static string lbl_Test_completed_date {
            get {
                return ResourceManager.GetString("lbl_Test_completed_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thử nghiệm.
        /// </summary>
        internal static string lbl_Test_duration {
            get {
                return ResourceManager.GetString("lbl_Test_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm kiểm thử.
        /// </summary>
        internal static string lbl_Test_type {
            get {
                return ResourceManager.GetString("lbl_Test_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chờ kết nối (giây).
        /// </summary>
        internal static string lbl_Timeout {
            get {
                return ResourceManager.GetString("lbl_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công suất tính bằng momen xoắn trên trục quạt.
        /// </summary>
        internal static string lbl_Torque_power_abs {
            get {
                return ResourceManager.GetString("lbl_Torque_power_abs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới library.
        /// </summary>
        internal static string title_Lib_new {
            get {
                return ResourceManager.GetString("title_Lib_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới kịch bản.
        /// </summary>
        internal static string title_Scenario_new {
            get {
                return ResourceManager.GetString("title_Scenario_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string txt_Password {
            get {
                return ResourceManager.GetString("txt_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        internal static string txt_UserName {
            get {
                return ResourceManager.GetString("txt_UserName", resourceCulture);
            }
        }
    }
}
